### ISSUE TITLE
Error in Xcode with AnthropicServiceFactory

### ISSUE THREAD

**Issue by iakar** [jamesrochabrun/SwiftAnthropic#14]
I am getting an Xcode error with this line:

let service = AnthropicServiceFactory.service(apiKey: apiKey, apiVersion: apiVersion)

Error:  Property definition has inferred type 'some AnthropicService', involving the 'some' return type of another declaration

I followed the instructions on git as precisely as possible.

**Comment by jamesrochabrun** [comment]
Can you try:

let service: AnthropicService = AnthropicServiceFactory.service(apiKey: apiKey, apiVersion: apiVersion)
