### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by elprl** [jamesrochabrun/SwiftAnthropic#17]
Can I suggest updating the APIError so that we can use error.localizedDescription, e.g.:

```swift
enum APIError: LocalizedError {
    public var errorDescription: String? { get }
}
```
 rather than creating a new property 'displayDescription' .

**Comment by elprl** [comment]
Also getting the following concatenation typo:
"status code 400Your credit balance is too low to access the Claude API. Please go to Plans & Billing to upgrade or purchase credits."

**Comment by elprl** [comment]
Here is what I'm doing currently:

```swift
extension SwiftAnthropic.APIError: LocalizedError, CustomStringConvertible {
    public var description: String {
        return displayDescription
    }
    
    /// A localized message describing what error occurred.
    public var errorDescription: String? {
        return displayDescription
    }
}
```

**Comment by jamesrochabrun** [comment]
Would you be open to create a pull request for this change? :)

**Comment by elprl** [comment]
I've edited the file and created the PR, but I've done no testing on this update.
`#18`
