### ISSUE TITLE
Is stream still not supported?

### ISSUE THREAD

**Issue by pradeepb28** [jamesrochabrun/SwiftAnthropic#19]
I happened to read streaming is not supported in beta based on the documentation but at the same time I also see the demo  video where streaming is working.  WHat is the current status of it? Thanks!

**Comment by jamesrochabrun** [comment]
you can check the demo https://github.com/jamesrochabrun/SwiftAnthropic/blob/main/Examples/SwiftAnthropicExample/SwiftAnthropicExample/Messages/MessageDemoView.swift#L82C1-L83C1
Yes, is supported
