### ISSUE TITLE
Tools with streaming not working

### ISSUE THREAD

**Issue by paulotaylor** [jamesrochabrun/SwiftAnthropic#20]
Claude already supports tools use with streaming but it doesn't seem to work with this library - https://www.anthropic.com/news/tool-use-ga

**Comment by jamesrochabrun** [comment]
Can you share your api request? thanks

**Comment by jamesrochabrun** [comment]
Did you saw this demo? https://github.com/jamesrochabrun/SwiftAnthropic/blob/main/Examples/SwiftAnthropicExample/SwiftAnthropicExample/FunctionCalling/MessageFunctionCallingDemoView.swift

**Comment by sakeven** [comment]
@jamesrochabrun The demo you provided does not seem to extract the toolResponse when calling streamMessage, so how do you obtain tool_use?

**Comment by jamesrochabrun** [comment]
Got it, this adds support for it https://github.com/jamesrochabrun/SwiftAnthropic/releases/tag/v1.7
