### ISSUE TITLE
Can't seem to disable all the debug logs for chunks received

### ISSUE THREAD

**Issue by provencher** [jamesrochabrun/SwiftAnthropic#22]
The library's debug logs are polluting my console and I'd like to remove them but don't see how.

Would be great to optionally suppress these logs in debug view as it's preventing me from debugging issues with my app.

**Comment by sakeven** [comment]
@jamesrochabrun 
As a library, I believe it should not use `#if DEBUG` to print logs, because the applications integrating the library also need to use `#if DEBUG` to print its debug logs. 
If the library uses it as well, it will result in a large number of logs mixed together. 
It's better to use a custom flag for logging, so that by default, the integrating party will not enable it.

**Comment by jamesrochabrun** [comment]
I agree I just did not had the time to update it! Contributions are welcome as well! 
I will try to find time this month.

**Comment by jamesrochabrun** [comment]
https://github.com/jamesrochabrun/SwiftAnthropic/releases/tag/v1.8 
@provencher @sakeven Done!

**Comment by sakeven** [comment]
@jamesrochabrun 
I see there are still some debug logs generated by printCurlCommand and printHTTPURLResponse.

**Comment by jamesrochabrun** [comment]
@sakeven make sure you are using [v1.8](https://github.com/jamesrochabrun/SwiftAnthropic/releases/tag/v1.8) or up. And set the flag to disabled false.

let service = AnthropicServiceFactory.service(apiKey: YOUR_API_KEY, debugEnabled: true)

**Comment by sakeven** [comment]
@jamesrochabrun I'm pretty sure I'm using v1.8.2 and already set debugEnabled false. I have reviewed your code and found that some debug information has not been disabled especially in [printCurlCommand:L308](https://github.com/jamesrochabrun/SwiftAnthropic/blob/main/Sources/Anthropic/Service/AnthropicService.swift#L308)
and [printHTTPURLResponse:L328](https://github.com/jamesrochabrun/SwiftAnthropic/blob/main/Sources/Anthropic/Service/AnthropicService.swift#L328)

**Comment by jamesrochabrun** [comment]
Got it, https://github.com/jamesrochabrun/SwiftAnthropic/releases/tag/v1.8.4
@sakeven thanks for flagging
