### ISSUE TITLE
Add support for cancellation tokens in the message stream api.

### ISSUE THREAD

**Issue by provencher** [jamesrochabrun/SwiftAnthropic#24]
I noticed that your stream doesn't support cancellations correctly.

You could do that by modifying your stream message api like so.

```
public func streamMessage(
   _ parameter: MessageParameter,
   withCancellationToken cancellationToken: CancellationToken)
   async throws -> AsyncThrowingStream<MessageStreamResponse, Error>
{
    // ... existing setup code ...

    return AsyncThrowingStream { continuation in
        let task = Task {
            do {
                for try await line in data.lines {
                    if cancellationToken.isCancelled {
                        throw CancellationError()
                    }
                    // ... existing processing code ...
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
        continuation.onTermination = { @Sendable _ in
            task.cancel()
        }
    }
}
```

**Comment by jamesrochabrun** [comment]
Will add support for it next week!

**Comment by jamesrochabrun** [comment]
Cancellation is supported, please check this demo https://github.com/jamesrochabrun/SwiftAnthropic/blob/46b32d98dc4ad319913be0e1ac1c78c93877c291/Examples/SwiftAnthropicExample/SwiftAnthropicExample/Messages/MessageDemoObservable.swift#L63

**Comment by provencher** [comment]
Huh so I did follow that example already and it's what my code does but I didn't see how that handled sending a cancellation token to the api. 

Afaik that just cancels the task but doesn't stop the api from continuing to produce tokens. I might be mistaken, but that's my perception.

**Comment by jamesrochabrun** [comment]
I see, you may be right! wIll take a look :)
