### ISSUE TITLE
output tokens appear to be miscalculated in streamed responses

### ISSUE THREAD

**Issue by froggomad** [jamesrochabrun/SwiftAnthropic#31]
When determining usage of a streamed generation using claude 3.5 sonnet, output tokens are always 1, even for very long generations. Input tokens appear to be calculated correctly.

```swift
for try await result in stream {
    if let usage = result.message?.usage {
        let inputTokens = usage.inputTokens
        let outputTokens = usage.outputTokens
        streamUsage.inputTokens += inputTokens
        streamUsage.outputTokens += outputTokens // 1
    }
}
```

**Comment by gdbing** [comment]
What's going on with your example code? `inputTokens` and `outputTokens` are both optionals, but you're not unwrapping them before `+=`ing them. I'm pretty sure the compiler won't let you even try this.

When you stream you get a bunch of results
- `message_start`
- `content_block_start`
- `content_block_delta`
- `content_block_delta`
- `content_block_delta`
- `content_block_stop`
- `message_delta`
- `message_stop`

The `input_tokens` of your input and `output_tokens` of 1 are in the `message_start` result. You seem to be successfully parsing those. The `output_tokens` of the response are in the `message_delta` result. You're failing to parse that.

I bet that what's happening is that in your actual code you have something like `if let inputTokens, let outputTokens {` to unwrap the `Int?`s but since `message_delta` has a nil `input_tokens` field, it doesn't pass the conditional and doesn't `+=` the `output_tokens` value.

Hope that helps.

**Comment by gdbing** [comment]
Nevermind, I was totally talking out of my ass. The problem is actually that you should get input tokens with `result.message?.usage.inputTokens` and get output tokens with `result.usage?.outputTokens`

https://docs.anthropic.com/en/api/messages-streaming#basic-streaming-request

```
event: message_start
data: {
	"type": "message_start", 
	"message": {
		"id": "msg_1nZdL29xx5MUA1yADyHTEsnR8uuvGzszyY", 
		"type": "message", 
		"role": "assistant", 
		"content": [], 
		"model": "claude-3-5-sonnet-20240620", 
		"stop_reason": null, 
		"stop_sequence": null, 
		"usage": {
			"input_tokens": 25, 
			"output_tokens": 1
		}
	}
}
```

```
event: message_delta
data: {
	"type": "message_delta", 
	"delta": {
		"stop_reason": "end_turn", 
		"stop_sequence":null
	}, 
	"usage": {
		"output_tokens": 15
	}
}
```

**Comment by kdubroff** [comment]
The sample code is unwrapping the `Usage` property of the `Message` property of the `Result`. How do I get `outputTokens` using your SDK?

**Comment by froggomad** [comment]
My sample code is doing what you're suggesting and the result is always 1. I stripped extraneous information - guess I went too far.

```swift
let stream = try await service.streamMessage(parameters)
do {
    for try await result in stream {
        if let usage = result.message?.usage {
            let inputTokens = usage.inputTokens
            let outputTokens = usage.outputTokens
            streamUsage.inputTokens += inputTokens
            streamUsage.outputTokens += outputTokens
            print("response output tokens: \(outputTokens)") // response output tokens: 1
            print("response input tokens: \(inputTokens)")
        }
    }
}
```

it seems like you're not parsing outputTokens from the message delta as these are never returned beyond the message start event.

**Comment by froggomad** [comment]
the `delta` property of `MessageStreamResponse` doesn't contain a `usage` parameter, so I'm not sure where else to look. Is your SDK capturing output tokens on message deltas?

**Comment by gdbing** [comment]
My [first response](https://github.com/jamesrochabrun/SwiftAnthropic/issues/31#issuecomment-2297529560) was wrong, read my [second one](https://github.com/jamesrochabrun/SwiftAnthropic/issues/31#issuecomment-2299665204) where I correct myself

> you should get input tokens with `result.message?.usage.inputTokens` and get output tokens with `result.usage?.outputTokens`

Just do this:
```
let stream = try await service.streamMessage(parameters)
do {
    for try await result in stream {
        if let inputTokens = result.message?.usage.inputTokens {
            streamUsage.inputTokens += inputTokens
            print("response input tokens: \(inputTokens)")
        }

        if let outputTokens = result.usage?.outputTokens {
            streamUsage.outputTokens += outputTokens
            print("response output tokens: \(outputTokens)")
        }
    }
}
```

**Comment by froggomad** [comment]
Ah, I see the problem now. I was using version 1.4.0 which doesn't have a usage property on `result`. Your 2nd response in JSON lead me to believe it might be there, but I wasn't seeing it in Swift, so assumed you must be handling it in a different way.
