### ISSUE TITLE
Missing `tool_choice` parameter

### ISSUE THREAD

**Issue by Lobidu** [jamesrochabrun/SwiftAnthropic#32]
The API offers a `tool_choice` parameter to force tool use:

https://docs.anthropic.com/en/docs/build-with-claude/tool-use#forcing-tool-use

I don't see this reflected in the specs here, or am I too dumb to find it?

**Comment by ahammouda** [comment]
Hey - I'm happy to submit a PR for this shortly.  I've been working with this locally

**Comment by ahammouda** [comment]
> Hey - I'm happy to submit a PR for this shortly. I've been working with this locally

https://github.com/jamesrochabrun/SwiftAnthropic/pull/33

**Comment by jamesrochabrun** [comment]
resolved on latest version
